kind: pipeline
name: amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: test
    image: ruby:2.5
    commands:
      - bundle install
      - bundle exec rspec
      - ./bin/flying-shuttle -h
  - name: docker
    image: plugins/docker
    settings:
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quay.io/kontena/weave-flying-shuttle-amd64
      dockerfile: Dockerfile
      auto_tag: true
    when:
      event: [tag, push]
---
kind: pipeline
name: arm64
platform:
  os: linux
  arch: arm64
steps:
  - name: test
    image: ruby:2.5
    commands:
      - bundle install
      - bundle exec rspec
      - ./bin/flying-shuttle -h
  - name: docker
    image: plugins/docker
    settings:
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quay.io/kontena/weave-flying-shuttle-arm64
      dockerfile: Dockerfile
      auto_tag: true
    when:
      event: [tag, push]
