kind: pipeline
name: amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: test
    image: ruby:2.5
    commands:
      - bundle install
      - bundle exec rspec
      - ./bin/flying-shuttle -h
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: hub_username
      password:
        from_secret: hub_password
      repo: docker.io/kontenapharos/weave-flying-shuttle-amd64
      dockerfile: Dockerfile
      auto_tag: true
    when:
      event: [tag, push]
---
kind: pipeline
name: arm64
platform:
  os: linux
  arch: arm64
steps:
  - name: test
    image: ruby:2.5
    commands:
      - bundle install
      - bundle exec rspec
      - ./bin/flying-shuttle -h
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: hub_username
      password:
        from_secret: hub_password
      repo: docker.io/kontenapharos/weave-flying-shuttle-arm64
      dockerfile: Dockerfile
      auto_tag: true
    when:
      event: [tag, push]
---
kind: pipeline
name: manifest
platform:
  os: linux
  arch: amd64
steps:
  - name: manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: hub_username
      password:
        from_secret: hub_password
      target: docker.io/kontenapharos/weave-flying-shuttle:${DRONE_TAG##v}
      template: docker.io/kontenapharos/weave-flying-shuttle-ARCH:${DRONE_TAG##v}
      platforms:
        - linux/amd64
        - linux/arm64
      ignore_missing: true
depends_on:
  - amd64
  - arm64
